### ISSUE TITLE
refactor occurs check into a folder

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/chalk#25]
The occurs check code in `src/solve/infer/unify.rs` (specifically, the methods defined on `OccursCheck`) follows a very folder-like pattern. Unfortunately, it can't quite use the `Folder` trait (as defined in `fold.rs`) because that trait only contains "callback methods" for processing free lifetime/type/krate variables. The occurs check needs to be able intercept all types, at least, as well as names that live in a universe and a few other things. We could add callback methods for those things to `Folder`. 

I imagine the resulting trait would look like:

```rust
pub trait Folder {
    // Methods today:
    fn fold_free_var(&mut self, depth: usize, binders: usize) -> Result<Ty>;
    fn fold_free_lifetime_var(&mut self, depth: usize, binders: usize) -> Result<Lifetime>;
    fn fold_free_krate_var(&mut self, depth: usize, binders: usize) -> Result<Krate>;

    // Methods we need:
    fn fold_ty(&mut self, ty: &Ty, binders: usize) -> Result<Ty>;
    fn fold_lifetime(&mut self, lifetime: &Lifetime, binders: usize) -> Result<Lifetime>;
}
```

One thing that I'm not crazy about is that `fold_ty` invokes `fold_free_var` etc, at least in its default incarnation, so putting them into the same trait might mean that if you override `fold_ty` you would not need the other methods. So it might be better to have `Folder` just include the higher-level methods (e.g., `fold_ty`) and then have a new trait `VarFolder` where we define a bridge impl like `impl<T: VarFolder> Folder for T`. Or something like that.

**Comment by fabric-and-ink** [comment]
I would like to give this a shot :)

**Comment by nikomatsakis** [comment]
@fabric-and-ink cool, feel free to come to gitter channel with questions, if any arise

**Comment by fabric-and-ink** [comment]
Slow but steady progress... :)

**Comment by fabric-and-ink** [comment]
I followed your suggestion to implement a bridge trait. Now I am stuck at connecting both kinds of folders at this point:

```
    fn fold_lifetime(&mut self, lifetime: &Lifetime, binders: usize) -> Result<Lifetime> {
        match *lifetime {
            Lifetime::Var(ref var) => {
                self.fold_free_lifetime_var(*var, binders)
            },
            Lifetime::ForAll(universe_index) => {
                unimplemented!();
            },
        }
    }
```
I don't know what a *universe* is in this context (see #51) and therefore don't now how to proceed. Any hints? :)

**Comment by nikomatsakis** [comment]
@fabric-and-ink sorry, missed these comments! Maybe post your branch somewhere I can see it?

**Comment by fabric-and-ink** [comment]
There you go: https://github.com/fabric-and-ink/chalk/commit/170609ac0ea158597d65d47a26e4f29f6f6bcc9a

**Comment by fabric-and-ink** [comment]
Replaced the old `Folder` trait (now `FolderVar`) with the new `Folder`. Now I am at [this point](https://github.com/fabric-and-ink/chalk/commit/30d7cb1c942f230593f8a3b6aff5ed919c15e48e). The "bride" impl and the impl for `Folder + ?Sized ...` are in conflict. But the second impl is necessary to make  for example [this](https://github.com/nikomatsakis/chalk/blob/master/src/fold/shifted.rs#L34-L35) work.

**Comment by fabric-and-ink** [comment]
@nikomatsakis any hints on how to solve the trait conflict? (See last comment.)

**Comment by scalexm** [comment]
@fabric-and-ink niko is not extremely available right now, but I'll try to help you soon :)

**Comment by scalexm** [comment]
@fabric-and-ink How about:
```rust
pub struct FolderRef<'f, F> where F: 'f + ?Sized {
    folder: &'f mut F,
}

impl<'f, F: ?Sized> FolderRef<'f, F> {
    pub fn new(folder: &'f mut F) -> Self {
        FolderRef {
            folder,
        }
    }
}

impl<'f, F: Folder + ?Sized> Folder for FolderRef<'f, F> {
    fn fold_ty(&mut self, ty: &Ty, binders: usize) -> Result<Ty> {
        self.folder.fold_ty(ty, binders)
    }

    fn fold_lifetime(&mut self, lifetime: &Lifetime, binders: usize) -> Result<Lifetime> {
        self.folder.fold_lifetime(lifetime, binders)
    }
}
```

and then you use like that:
```rust
impl<T: Fold> Fold for Shifted<T> {
    type Result = T::Result;

    fn fold_with(&self, folder: &mut Folder, binders: usize) -> Result<Self::Result> {
        // I... think this is right if binders is not zero, but not sure,
        // and don't care to think about it.
        assert_eq!(binders, 0);

        // First up-shift any variables. i.e., if `self.value`
        // contains a free var with index 0, and `self.adjustment ==
        // 2`, we will translate it to a free var with index 2; then
        // we will fold *that* through `folder`.
        let mut new_folder = (Shifter::new(self.adjustment), FolderRef::new(folder));
        self.value.fold_with(&mut new_folder, binders)
    }
}
```

With that I think you should be good :)

**Comment by fabric-and-ink** [comment]
Nice! Thank you! That worked well :)
